2022-01-11 11:12:42,941 INFO    MainThread:47436 [internal.py:wandb_internal():90] W&B internal server running at pid: 47436, started at: 2022-01-11 11:12:42.941057
2022-01-11 11:12:42,945 DEBUG   HandlerThread:47436 [handler.py:handle_request():130] handle_request: check_version
2022-01-11 11:12:42,945 INFO    WriterThread:47436 [datastore.py:open_for_write():77] open: E:\Pytorch-UNet\wandb\run-20220111_111240-vaaidps5\run-vaaidps5.wandb
2022-01-11 11:12:42,952 DEBUG   SenderThread:47436 [sender.py:send():238] send: header
2022-01-11 11:12:42,952 DEBUG   SenderThread:47436 [sender.py:send_request():252] send_request: check_version
2022-01-11 11:12:44,307 DEBUG   SenderThread:47436 [sender.py:send():238] send: run
2022-01-11 11:12:44,314 INFO    SenderThread:47436 [sender.py:_maybe_setup_resume():506] checking resume status for None/U-Net/vaaidps5
2022-01-11 11:12:44,457 WARNING MainThread:47436 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-11 11:12:45,103 INFO    SenderThread:47436 [dir_watcher.py:__init__():169] watching files in: E:\Pytorch-UNet\wandb\run-20220111_111240-vaaidps5\files
2022-01-11 11:12:45,104 INFO    SenderThread:47436 [sender.py:_start_run_threads():828] run started: vaaidps5 with start time 1641870761
