2021-12-09 17:23:09,156 INFO    MainThread:33264 [wandb_setup.py:_flush():71] setting env: {}
2021-12-09 17:23:09,156 INFO    MainThread:33264 [wandb_setup.py:_flush():71] setting login settings: {'anonymous': 'must'}
2021-12-09 17:23:09,156 INFO    MainThread:33264 [wandb_init.py:_log_setup():371] Logging user logs to E:\Pytorch-UNet\wandb\run-20211209_172309-3migzs6z\logs\debug.log
2021-12-09 17:23:09,157 INFO    MainThread:33264 [wandb_init.py:_log_setup():372] Logging internal logs to E:\Pytorch-UNet\wandb\run-20211209_172309-3migzs6z\logs\debug-internal.log
2021-12-09 17:23:09,157 INFO    MainThread:33264 [wandb_init.py:init():404] calling init triggers
2021-12-09 17:23:09,157 INFO    MainThread:33264 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-12-09 17:23:09,158 INFO    MainThread:33264 [wandb_init.py:init():449] starting backend
2021-12-09 17:23:09,158 INFO    MainThread:33264 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-12-09 17:23:09,163 INFO    MainThread:33264 [backend.py:ensure_launched():199] starting backend process...
2021-12-09 17:23:09,265 INFO    MainThread:33264 [backend.py:ensure_launched():205] started backend process with pid: 40956
2021-12-09 17:23:09,265 INFO    MainThread:33264 [wandb_init.py:init():458] backend started and connected
2021-12-09 17:23:09,267 INFO    MainThread:33264 [wandb_init.py:init():519] updated telemetry
2021-12-09 17:23:09,340 INFO    MainThread:33264 [wandb_init.py:init():549] communicating current version
2021-12-09 17:23:10,436 INFO    MainThread:33264 [wandb_init.py:init():554] got version response 
2021-12-09 17:23:10,436 INFO    MainThread:33264 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-09 17:23:18,497 WARNING MainThread:33264 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\wandb_init.py", line 917, in init
    run = wi.init()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\wandb_init.py", line 565, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface.py", line 205, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 334, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\interface\router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
