2022-01-11 10:45:57,813 INFO    MainThread:59620 [internal.py:wandb_internal():90] W&B internal server running at pid: 59620, started at: 2022-01-11 10:45:57.813004
2022-01-11 10:45:57,819 INFO    WriterThread:59620 [datastore.py:open_for_write():77] open: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\run-2erz6bop.wandb
2022-01-11 10:45:57,820 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: check_version
2022-01-11 10:45:57,828 DEBUG   SenderThread:59620 [sender.py:send():238] send: header
2022-01-11 10:45:57,828 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: check_version
2022-01-11 10:45:59,194 DEBUG   SenderThread:59620 [sender.py:send():238] send: run
2022-01-11 10:45:59,201 INFO    SenderThread:59620 [sender.py:_maybe_setup_resume():506] checking resume status for None/U-Net/2erz6bop
2022-01-11 10:46:00,003 INFO    SenderThread:59620 [dir_watcher.py:__init__():169] watching files in: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files
2022-01-11 10:46:00,004 INFO    SenderThread:59620 [sender.py:_start_run_threads():828] run started: 2erz6bop with start time 1641869156
2022-01-11 10:46:00,004 DEBUG   SenderThread:59620 [sender.py:send():238] send: summary
2022-01-11 10:46:00,005 INFO    SenderThread:59620 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-01-11 10:46:00,007 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: run_start
2022-01-11 10:46:00,058 DEBUG   HandlerThread:59620 [meta.py:__init__():40] meta init
2022-01-11 10:46:00,059 DEBUG   HandlerThread:59620 [meta.py:__init__():54] meta init done
2022-01-11 10:46:00,059 DEBUG   HandlerThread:59620 [meta.py:probe():214] probe
2022-01-11 10:46:00,182 DEBUG   HandlerThread:59620 [meta.py:_setup_git():204] setup git
2022-01-11 10:46:00,353 DEBUG   HandlerThread:59620 [meta.py:_setup_git():211] setup git done
2022-01-11 10:46:00,354 DEBUG   HandlerThread:59620 [meta.py:_save_pip():58] save pip
2022-01-11 10:46:00,355 DEBUG   HandlerThread:59620 [meta.py:_save_pip():72] save pip done
2022-01-11 10:46:00,356 DEBUG   HandlerThread:59620 [meta.py:_save_conda():79] save conda
2022-01-11 10:46:01,013 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\requirements.txt
2022-01-11 10:46:01,014 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\conda-environment.yaml
2022-01-11 10:46:01,014 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\wandb-summary.json
2022-01-11 10:46:06,022 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\output.log
2022-01-11 10:46:08,026 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\output.log
2022-01-11 10:46:09,028 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\conda-environment.yaml
2022-01-11 10:46:10,646 DEBUG   HandlerThread:59620 [meta.py:_save_conda():89] save conda done
2022-01-11 10:46:10,647 DEBUG   HandlerThread:59620 [meta.py:probe():252] probe done
2022-01-11 10:46:10,662 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:46:10,662 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:46:11,030 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\conda-environment.yaml
2022-01-11 10:46:11,031 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_created():217] file/dir created: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\wandb-metadata.json
2022-01-11 10:46:11,062 DEBUG   SenderThread:59620 [sender.py:send():238] send: config
2022-01-11 10:46:11,062 DEBUG   SenderThread:59620 [sender.py:send():238] send: files
2022-01-11 10:46:11,063 INFO    SenderThread:59620 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-01-11 10:46:12,141 INFO    Thread-22 :59620 [upload_job.py:push():137] Uploaded file C:\Users\211001~1.WXC\AppData\Local\Temp\tmp9bc3r8p4wandb\3tupzp93-wandb-metadata.json
2022-01-11 10:46:25,029 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:46:25,030 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:46:29,083 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\config.yaml
2022-01-11 10:46:30,230 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:46:38,097 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\output.log
2022-01-11 10:46:40,442 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:46:40,443 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:46:55,843 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:46:55,843 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:47:01,663 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:47:11,226 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:47:11,227 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:47:26,616 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:47:26,617 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:47:34,136 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:47:46,618 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:47:46,618 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:48:01,994 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:48:01,995 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:48:04,362 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:48:17,361 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:48:17,361 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:48:32,729 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:48:32,730 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:48:35,725 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:48:48,095 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:48:48,096 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:49:03,493 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:49:03,494 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:49:07,018 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:49:18,895 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:49:18,895 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:49:34,268 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:49:34,268 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:49:35,386 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\output.log
2022-01-11 10:49:38,371 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:49:49,647 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:49:49,648 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:50:03,421 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\output.log
2022-01-11 10:50:05,019 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:50:05,020 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:50:09,744 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:50:20,397 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:50:20,397 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:50:35,991 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:50:35,991 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:50:41,537 DEBUG   SenderThread:59620 [sender.py:send():238] send: stats
2022-01-11 10:50:51,384 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:50:51,384 DEBUG   SenderThread:59620 [sender.py:send_request():252] send_request: stop_status
2022-01-11 10:50:54,836 ERROR   SenderThread:59620 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connection.py", line 507, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\anaconda3\envs\Pytorch-UNet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\2110012.WXCNL-5887\AppData\Roaming\Python\Python36\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
2022-01-11 10:51:11,385 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:51:31,388 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:51:31,865 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:51:34,362 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:51:39,115 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:51:48,899 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:51:51,390 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:52:08,763 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:52:11,392 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:52:31,394 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:52:47,455 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:52:51,406 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:53:11,407 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:53:31,410 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:53:51,412 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:53:57,256 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:54:11,414 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:54:31,415 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:54:51,417 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:55:11,419 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:55:31,421 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:55:51,424 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:56:11,427 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: stop_status
2022-01-11 10:56:20,644 WARNING MainThread:59620 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-11 10:56:21,339 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:21,395 INFO    Thread-17 :59620 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\Pytorch-UNet\wandb\run-20220111_104554-2erz6bop\files\output.log
2022-01-11 10:56:26,485 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:31,588 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:36,337 WARNING FileStreamThread:59620 [file_stream.py:request_with_retry():570] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-169537/U-Net/2erz6bop/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000018FFF65D2E8>>, args: ('https://api.wandb.ai/files/anony-mouse-169537/U-Net/2erz6bop/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-01-11 10:56:36,689 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:41,790 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:46,891 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:51,993 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:56:57,095 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:02,196 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:07,299 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:12,400 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:17,507 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:22,609 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:27,711 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:32,813 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:37,915 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:43,017 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:48,119 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:53,219 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:57:58,321 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:03,422 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:08,525 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:13,627 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:18,729 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:23,830 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:28,931 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:34,034 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:39,137 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:44,240 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:49,342 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:54,444 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:58:59,550 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:04,677 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:09,752 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:14,853 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:19,954 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:25,057 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:30,159 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:35,260 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:40,362 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:45,462 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:50,564 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 10:59:55,666 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 11:00:00,768 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 11:00:05,870 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 11:00:10,972 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
2022-01-11 11:00:16,076 DEBUG   HandlerThread:59620 [handler.py:handle_request():130] handle_request: poll_exit
